In [2]:
import pandas as pd
df = pd.read_csv("D:/tiger analytics/Python/consumer behavior/ecommerce_customer_behavior_dataset_v2.csv")

In [3]:
df["Date"] = pd.to_datetime(df["Date"])

C:\Users\91966\AppData\Local\Temp\ipykernel_10824\936118274.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"] = pd.to_datetime(df["Date"])

In [4]:
clv_df = df.groupby("Customer_ID").agg({
    "Total_Amount": "sum",      # Total revenue
    "Order_ID": "count",        # Number of orders
    "Date": ["min", "max"]      # Customer lifespan
})

In [5]:
clv_df.head()

            Total_Amount Order_ID       Date
                     sum    count        min        max
Customer_ID
CUST_00001       2199.63        3 2023-05-29 2023-12-05
CUST_00002        809.90        2 2023-05-11 2023-06-16
CUST_00003       3030.81        2 2023-02-27 2024-01-03
CUST_00004        383.22        1 2024-02-13 2024-02-13
CUST_00005       2422.73        3 2023-03-16 2023-06-21

In [6]:
clv_df.columns = ["Total_Revenue", "Total_Orders", "First_Order", "Last_Order"]

In [7]:
clv_df["AOV"] = clv_df["Total_Revenue"] / clv_df["Total_Orders"]

In [8]:
clv_df["Lifespan_Days"] = (clv_df["Last_Order"] - clv_df["First_Order"]).dt.days + 1

In [9]:
clv_df.head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days
Customer_ID,,,,,,
CUST_00001,2199.63,3,2023-05-29,2023-12-05,733.210000,191
CUST_00002,809.90,2,2023-05-11,2023-06-16,404.950000,37
CUST_00003,3030.81,2,2023-02-27,2024-01-03,1515.405000,311
CUST_00004,383.22,1,2024-02-13,2024-02-13,383.220000,1
CUST_00005,2422.73,3,2023-03-16,2023-06-21,807.576667,98

In [10]:
clv_df["CLV"] = clv_df["AOV"] * clv_df["Total_Orders"]

In [11]:
clv_df.head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV
Customer_ID,,,,,,,
CUST_00001,2199.63,3,2023-05-29,2023-12-05,733.210000,191,2199.63
CUST_00002,809.90,2,2023-05-11,2023-06-16,404.950000,37,809.90
CUST_00003,3030.81,2,2023-02-27,2024-01-03,1515.405000,311,3030.81
CUST_00004,383.22,1,2024-02-13,2024-02-13,383.220000,1,383.22
CUST_00005,2422.73,3,2023-03-16,2023-06-21,807.576667,98,2422.73

In [12]:
clv_df["Monthly_Frequency"] = clv_df["Total_Orders"] / (clv_df["Lifespan_Days"] / 30)

clv_df["Improved_CLV"] = clv_df["AOV"] * clv_df["Monthly_Frequency"] * 12

In [13]:
clv_df.head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV,Monthly_Frequency,Improved_CLV
Customer_ID,,,,,,,,,
CUST_00001,2199.63,3,2023-05-29,2023-12-05,733.210000,191,2199.63,0.471204,4145.899476
CUST_00002,809.90,2,2023-05-11,2023-06-16,404.950000,37,809.90,1.621622,7880.108108
CUST_00003,3030.81,2,2023-02-27,2024-01-03,1515.405000,311,3030.81,0.192926,3508.333119
CUST_00004,383.22,1,2024-02-13,2024-02-13,383.220000,1,383.22,30.000000,137959.200000
CUST_00005,2422.73,3,2023-03-16,2023-06-21,807.576667,98,2422.73,0.918367,8899.824490

In [14]:
clv_df.sort_values("Improved_CLV", ascending=False).head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV,Monthly_Frequency,Improved_CLV
Customer_ID,,,,,,,,,
CUST_01399,18284.96,1,2024-01-31,2024-01-31,18284.96,1,18284.96,30.0,6582585.6
CUST_01578,16999.50,1,2023-02-26,2023-02-26,16999.50,1,16999.50,30.0,6119820.0
CUST_03856,14532.72,1,2023-04-04,2023-04-04,14532.72,1,14532.72,30.0,5231779.2
CUST_03579,14501.20,1,2023-08-23,2023-08-23,14501.20,1,14501.20,30.0,5220432.0
CUST_00250,12718.20,1,2023-10-02,2023-10-02,12718.20,1,12718.20,30.0,4578552.0

In [15]:
clv_df.sort_values("Total_Revenue", ascending=False).head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV,Monthly_Frequency,Improved_CLV
Customer_ID,,,,,,,,,
CUST_01573,50628.15,2,2024-03-01,2024-03-23,25314.075000,23,50628.15,2.608696,792440.608696
CUST_00197,47324.23,10,2023-01-04,2024-01-13,4732.423000,375,47324.23,0.800000,45431.260800
CUST_03795,42480.02,3,2023-02-06,2024-02-07,14160.006667,367,42480.02,0.245232,41669.774387
CUST_00154,41613.83,10,2023-01-04,2024-02-24,4161.383000,417,41613.83,0.719424,35925.608633
CUST_04219,40608.39,8,2023-02-01,2024-02-09,5076.048750,374,40608.39,0.641711,39088.289840

In [16]:
clv_df.sort_values("AOV", ascending=False).head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV,Monthly_Frequency,Improved_CLV
Customer_ID,,,,,,,,,
CUST_01573,50628.15,2,2024-03-01,2024-03-23,25314.075,23,50628.15,2.608696,7.924406e+05
CUST_01399,18284.96,1,2024-01-31,2024-01-31,18284.960,1,18284.96,30.000000,6.582586e+06
CUST_01578,16999.50,1,2023-02-26,2023-02-26,16999.500,1,16999.50,30.000000,6.119820e+06
CUST_03084,29427.77,2,2023-02-20,2023-11-08,14713.885,262,29427.77,0.229008,4.043510e+04
CUST_02856,29249.71,2,2023-02-28,2023-09-21,14624.855,206,29249.71,0.291262,5.111600e+04

In [17]:
behavior_df = df.groupby("Customer_ID").agg({
    "Session_Duration_Minutes": "mean",
    "Pages_Viewed": "mean",
    "Customer_Rating": "mean",
    "Is_Returning_Customer": "max"    # if returning at least once, consider as returning
})
behavior_df.columns = [
    "Avg_Session_Duration",
    "Avg_Pages_Viewed",
    "Avg_Rating",
    "Is_Returning_Customer"
]

In [18]:
behavior_df.head()

,Avg_Session_Duration,Avg_Pages_Viewed,Avg_Rating,Is_Returning_Customer
Customer_ID,,,,
CUST_00001,14.333333,9.000000,3.333333,True
CUST_00002,15.000000,10.000000,4.000000,True
CUST_00003,10.500000,8.500000,3.500000,True
CUST_00004,16.000000,15.000000,5.000000,False
CUST_00005,12.666667,9.333333,3.666667,True

In [19]:
demo_df = df.groupby("Customer_ID").agg({
    "Age": "max",
    "Gender": "max",
    "City": "max"
})

In [20]:
customer_df = clv_df.join(behavior_df).join(demo_df)

In [21]:
customer_df.head()

,Total_Revenue,Total_Orders,First_Order,Last_Order,AOV,Lifespan_Days,CLV,Monthly_Frequency,Improved_CLV,Avg_Session_Duration,Avg_Pages_Viewed,Avg_Rating,Is_Returning_Customer,Age,Gender,City
Customer_ID,,,,,,,,,,,,,,,,
CUST_00001,2199.63,3,2023-05-29,2023-12-05,733.210000,191,2199.63,0.471204,4145.899476,14.333333,9.000000,3.333333,True,40,Male,Ankara
CUST_00002,809.90,2,2023-05-11,2023-06-16,404.950000,37,809.90,1.621622,7880.108108,15.000000,10.000000,4.000000,True,33,Male,Istanbul
CUST_00003,3030.81,2,2023-02-27,2024-01-03,1515.405000,311,3030.81,0.192926,3508.333119,10.500000,8.500000,3.500000,True,42,Male,Konya
CUST_00004,383.22,1,2024-02-13,2024-02-13,383.220000,1,383.22,30.000000,137959.200000,16.000000,15.000000,5.000000,False,53,Male,Izmir
CUST_00005,2422.73,3,2023-03-16,2023-06-21,807.576667,98,2422.73,0.918367,8899.824490,12.666667,9.333333,3.666667,True,32,Male,Ankara

In [24]:
# Optional: encode categorical values
customer_df["Gender"] = customer_df["Gender"].astype("category").cat.codes
customer_df["City"] = customer_df["City"].astype("category").cat.codes
customer_df["Is_Returning_Customer"] = customer_df["Is_Returning_Customer"].astype("category").cat.codes

In [25]:
print(customer_df.head())
print(customer_df.shape)

             Total_Revenue  Total_Orders First_Order Last_Order          AOV  \
Customer_ID
CUST_00001         2199.63             3  2023-05-29 2023-12-05   733.210000
CUST_00002          809.90             2  2023-05-11 2023-06-16   404.950000
CUST_00003         3030.81             2  2023-02-27 2024-01-03  1515.405000
CUST_00004          383.22             1  2024-02-13 2024-02-13   383.220000
CUST_00005         2422.73             3  2023-03-16 2023-06-21   807.576667

             Lifespan_Days      CLV  Monthly_Frequency   Improved_CLV  \
Customer_ID
CUST_00001             191  2199.63           0.471204    4145.899476
CUST_00002              37   809.90           1.621622    7880.108108
CUST_00003             311  3030.81           0.192926    3508.333119
CUST_00004               1   383.22          30.000000  137959.200000
CUST_00005              98  2422.73           0.918367    8899.824490

             Avg_Session_Duration  Avg_Pages_Viewed  Avg_Rating  \
Customer_ID
CUST_00001              14.333333          9.000000    3.333333
CUST_00002              15.000000         10.000000    4.000000
CUST_00003              10.500000          8.500000    3.500000
CUST_00004              16.000000         15.000000    5.000000
CUST_00005              12.666667          9.333333    3.666667

             Is_Returning_Customer  Age  Gender  City
Customer_ID
CUST_00001                       1   40       1     1
CUST_00002                       1   33       1     6
CUST_00003                       1   42       1     9
CUST_00004                       0   53       1     7
CUST_00005                       1   32       1     1
(5000, 16)

In [26]:
customer_df = customer_df.drop(columns=["First_Order", "Last_Order"])

In [27]:
print(customer_df.head())

             Total_Revenue  Total_Orders          AOV  Lifespan_Days      CLV  \
Customer_ID
CUST_00001         2199.63             3   733.210000            191  2199.63
CUST_00002          809.90             2   404.950000             37   809.90
CUST_00003         3030.81             2  1515.405000            311  3030.81
CUST_00004          383.22             1   383.220000              1   383.22
CUST_00005         2422.73             3   807.576667             98  2422.73

             Monthly_Frequency   Improved_CLV  Avg_Session_Duration  \
Customer_ID
CUST_00001            0.471204    4145.899476             14.333333
CUST_00002            1.621622    7880.108108             15.000000
CUST_00003            0.192926    3508.333119             10.500000
CUST_00004           30.000000  137959.200000             16.000000
CUST_00005            0.918367    8899.824490             12.666667

             Avg_Pages_Viewed  Avg_Rating  Is_Returning_Customer  Age  Gender  \
Customer_ID
CUST_00001           9.000000    3.333333                      1   40       1
CUST_00002          10.000000    4.000000                      1   33       1
CUST_00003           8.500000    3.500000                      1   42       1
CUST_00004          15.000000    5.000000                      0   53       1
CUST_00005           9.333333    3.666667                      1   32       1

             City
Customer_ID
CUST_00001      1
CUST_00002      6
CUST_00003      9
CUST_00004      7
CUST_00005      1